apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp
  title: "Ksquare IDP"
  description: Internal developer platform for the Ksquare Group, built on Backstage
  annotations:
    github.com/project-slug: ksquare-platform/idp-backstage
    backstage.io/source-location: url:https://github.com/ksquare-platform/idp-backstage/tree/main/
    backstage.io/techdocs-ref: dir:.
    ksquare.io/deploy-environments: |
      staging: idp-deploy-test.yml@main
  tags:
    - "backstage"
    - "typescript"
    - "platform"
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-admins
